project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: cv/cv-catalina-medina.pdf
        text: CV

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

