project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: cv/cv-catalina-medina.pdf
        text: CV
      - href: resources.qmd
        text: Resources
    right:
      - icon: github
        href: https://github.com/CatalinaMedina/CatalinaMedina.github.io
  search: false
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

